version: "3"
services:
  angularproject:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-project
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/app-ui/node_modules
    networks:
      - angular-django

  djangobackend:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: /start
    container_name: djangobackend
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - postgres
      - mailhog
      - redis
    restart: "on-failure"
    networks:
      - angular-django

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres
    networks:
      - angular-django

  flower:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: /start-flower
    container_name: flower
    volumes:
      - .:/app
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres
      - celery_worker
    networks:
      - angular-django

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - angular-django

  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - angular-django

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: /start-celeryworker
    container_name: celery_worker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - redis
      - postgres
      - mailhog
    networks:
      - angular-django

  nginx:
    restart: always
    depends_on:
      - djangobackend
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80

    networks:
      - angular-django

networks:
  angular-django:
    driver: bridge

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  static_volume:
  media_volume:
